### ISSUE TITLE
How to get the proxy's source code?

### ISSUE THREAD

**Issue by elftech** [fholzer/docker-quic-reverse-proxy#2]

**Comment by fholzer** [comment]
Check the `Dockerfile`.

quic library at https://github.com/fholzer/goquic, the proxy source code at 
https://github.com/devsisters/goquic/blob/master/example/reverse_proxy.go.

Though I'm afraid this version of quic is outdated already. I suggest you checkout https://github.com/fholzer/go-quic-reverse-proxy. It's using [Lucas Clemente's quick-go](https://github.com/lucas-clemente/quic-go), though it's not easy to build if you're not familiar with Go.
